[simulation]
tableWidth = 224
tableHeight = 112
whiteBallCoords = [ 56.0, 56.0,]
whiteBallVx = 200.0
ballMass = 165
ballDiameter = 5.7
verbose = false

[files]
staticInput = "./static.txt"
output = "./out/output.txt"

[benchmarks]
whiteBallYRange = [ 42, 56,]
whiteBallVxRange = [ 100, 300,]
initialPositions = 3
initialVelocities = 10
rounds = 15
